# Generated by Django 3.0 on 2024-04-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='escolaridade',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
